FROM kylemanna/openvpn
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
         sed -i '/testing/d' /etc/apk/repositories && \
         apk update && \
	 apk add build-base && \ 
         apk add libgcrypt && \
         apk add libstdc++ && \
         apk add libgcrypt-dev && \
	 wget https://www.nongnu.org/radiusplugin/radiusplugin_v2.1a_beta1.tar.gz && \
	tar xf radiusplugin_v2.1a_beta1.tar.gz  && \
        cd radiusplugin_v2.1a_beta1 && \
	make && \
	cp radiusplugin.so /etc/openvpn/ && \
       cp radiusplugin.cnf /etc/openvpn/ && \
       rm -f ../radiusplugin_v2.1a_beta1.tar.gz && cd .. && rm -rf  radiusplugin_v2.1a_beta1
